### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by phillycc** [phillycc/ngFlickrSearchr#1]
- [x] Form validates that user supplied text input
- [x] When a user clicks submit, the text field in the form is cleared and text appears that indicates flickr is being queried.
- [x] The app should query the flickr API and search for recent pictures tagged with the term the user has supplied in the form.
- [ ] When the API results return, the app should tell the user how many results were returned, and display the photos (if any).
- [ ] You should be able to navigate to the original photo on flickr by clicking on any one of the images that appear.
- [ ] Your app must use at least one animation. It's up to you to decide where to put this.
- [ ] In case your calls to the server fail for some reason, the app should somehow alert the user.
- [x] Users should be able to submit another search after one has completed.
